# Configuration for Alacritty, the GPU enhanced terminal emulator

# Environment variables
[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 40 }
padding = { x = 6, y = 6 }
dynamic_padding = true
dynamic_title = true
opacity = 0.95
decorations = "full"
startup_mode = "Windowed"
title = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "FiraCode Nerd Font, Menlo", style = "Regular" }
bold = { family = "FiraCode Nerd Font, Menlo", style = "Bold" }
italic = { family = "FiraCode Nerd Font, Menlo", style = "Italic" }
size = 18.0

[font.offset]
x = 1
y = 1

[colors.primary]
background = "0x1e2127"
foreground = "0xabb2bf"

[colors.normal]
black = "0x1e2127"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xabb2bf"

[colors.bright]
black = "0x5c6370"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xffffff"

[bell]
animation = "EaseOutExpo"
duration = 0
color = "0xffffff"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = false

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = false

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false

[[keyboard.bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"
